# Generated by Django 5.0.6 on 2024-05-12 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="category", old_name="name", new_name="category_name",
        ),
        migrations.RenameField(
            model_name="product", old_name="name", new_name="product_name",
        ),
        migrations.RenameField(
            model_name="product", old_name="sub_category", new_name="sub_category_name",
        ),
        migrations.RenameField(
            model_name="subcategory", old_name="category", new_name="sub_category",
        ),
        migrations.RenameField(
            model_name="subcategory", old_name="name", new_name="sub_category_name",
        ),
    ]
