# Generated by Django 5.0.6 on 2024-05-12 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_rename_name_category_category_name_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="subcategory", old_name="sub_category", new_name="category",
        ),
    ]
