# Generated by Django 5.0.6 on 2024-05-18 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0007_cart_wishlist"),
    ]

    operations = [
        migrations.RemoveField(model_name="orders", name="quantity",),
    ]
