# Generated by Django 5.0.3 on 2024-05-26 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0009_customer_remove_orders_customer_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BasePoster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=50, null=True)),
                ("image", models.ImageField(upload_to="uploads/base")),
            ],
        ),
    ]
