# Generated by Django 5.0.3 on 2024-05-28 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0011_wishlistitem_delete_wishlist"),
    ]

    operations = [
        migrations.AddField(
            model_name="productdetail",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="uploads/products/details/"
            ),
        ),
    ]
