# Generated by Django 5.0.6 on 2024-06-01 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0014_remove_cart_product_name_cart_product_cart_quantity_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product", old_name="sub_category_name", new_name="sub_category",
        ),
        migrations.RenameField(
            model_name="subcategory",
            old_name="sub_category_name",
            new_name="sub_category",
        ),
    ]
