# Generated by Django 5.0.6 on 2024-06-02 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0015_rename_sub_category_name_product_sub_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="size",
            field=models.CharField(default="M", max_length=10),
        ),
    ]
