# Generated by Django 5.0.6 on 2024-06-02 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0016_cart_size"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="total_price",
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="price",
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(decimal_places=0, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name="product",
            name="sale_price",
            field=models.DecimalField(decimal_places=0, default=0, max_digits=8),
        ),
    ]
